### ISSUE TITLE
Does not work with toot.funami.tech

### ISSUE THREAD

**Issue by NoaHimesaka1873** [hyunbinseo/stod.one#1]
https://stod.one/@noahimesaka1873@toot.funami.tech
Expected result: redirect
Actual result: 404

**Comment by hyunbinseo** [comment]
Fixed in https://github.com/hyunbinseo/stod.one/commit/18735494d8900c03da5dc13e8bc73c3bc8dc062d

Thank you.

**Comment by hyunbinseo** [comment]
@NoaHimesaka1873 Now both URLs with and without subdomain work.

https://stod.one/@noahimesaka1873@toot.funami.tech
https://stod.one/@noahimesaka1873@funami.tech

Fixed in https://github.com/hyunbinseo/stod.one/commit/037bd37f263fc7f1a2fd64c47416a1c74df77834
